# -*- coding: utf-8 -*-
"""object detect .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kSWe9YuniK-kaRA9Lt6l5i0EDINANUxT
"""

from google.colab import drive
drive.mount('/content/drive')

!ls '/content/drive/MyDrive/yolo training'

#!unzip '/content/drive/MyDrive/yolo training/images.zip' -d '/content/drive/MyDrive/yolo training'

#!git clone 'https://github.com/AlexeyAB/darknet.git' '/content/drive/MyDrive/yolo training/darknet'

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/yolo training/darknet

# CUDA: Let's check that Nvidia CUDA drivers are already pre-installed and which version is it.
!/usr/local/cuda/bin/nvcc --version
# We need to install the correct cuDNN according to this output

!nvidia-smi

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/yolo training/darknet
!sed -i 's/OPENCV=0/OPENCV=1/g' Makefile
!sed -i 's/GPU=0/GPU=1/g' Makefile
!sed -i 's/CUDNN=0/CUDNN=1/g' Makefile
!sed -i "s/ARCH= -gencode arch=compute_60,code=sm_60/ARCH= ${ARCH_VALUE}/g" Makefile
!make

!darknet/darknet

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/yolo training

!python images/filesdata.py

!python images/trainandtest-txt-files.py

!darknet/darknet detector train images/labelled_data.data darknet/cfg/yolov4_custom.cfg custom_weights/yolov4.conv.137 -dont_show



